workflows:
  android:
    name: Android Build Workflow
    environment:
      vars:
        PROJECT_NAME: "MyReactNativeApp" # Replace with your project name
      flutter: stable
      android:
        ndk: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "ikram.ul.haqrmit.edu.au" # Replace with your email to receive build status
